{% set name = "alamode" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ttadano/{{ name }}/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: 3d1378ab37477e1cf393d1419edf4a887206c36bf1afb6913436451df55dec8c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - libblas
    - liblapack
    - openmpi
    - h5py
    - scipy
    - numpy
    - boost
    - eigen
    - spglib
    - fftw
  run:
    - python

test:
  files:
    - si_alm.in
    - si_phband.in
    - si222.xml
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - alm si_alm.in
    - anphon si_phband.in

about:
  home: https://github.com/ttadano/alamode
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ab initio simulator for thermal transport and lattice anharmonicity
  description: |
    ALAMODE is a scientific software designed for analyzing lattice
    anharmonicity and lattice thermal conductivity of solids. By
    using an external DFT package such as VASP and Quantum ESPRESSO, you 
    can extract harmonic and anharmonic force constants straightforwardly
    with ALAMODE. Using the calculated anharmonic force constants, you can
    also estimate lattice thermal conductivity, phonon linewidth, and 
    other anharmonic phonon properties from first principles.
  doc_url: https://alamode.readthedocs.io/
  dev_url: https://github.com/ttadano/alamode

extra:
  recipe-maintainers:
    - jan-janssen
